// flow-typed signature: 85288b7d01815ff54aff08b0f2a3f9b2
// flow-typed version: <<STUB>>/@backtrack/preset-node-module_v^0.1.11/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@backtrack/preset-node-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@backtrack/preset-node-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@backtrack/preset-node-module/lib/ci-run-flow' {
  declare module.exports: any;
}

declare module '@backtrack/preset-node-module/lib/files/babelrc-flow' {
  declare module.exports: any;
}

declare module '@backtrack/preset-node-module/lib/files/babelrc' {
  declare module.exports: any;
}

declare module '@backtrack/preset-node-module/lib/files/package-entry-flow' {
  declare module.exports: any;
}

declare module '@backtrack/preset-node-module/lib/files/package-entry' {
  declare module.exports: any;
}

declare module '@backtrack/preset-node-module/lib/preset-node-module' {
  declare module.exports: any;
}

declare module '@backtrack/preset-node-module/lib/preset-node-module.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@backtrack/preset-node-module/lib/ci-run-flow.js' {
  declare module.exports: $Exports<'@backtrack/preset-node-module/lib/ci-run-flow'>;
}
declare module '@backtrack/preset-node-module/lib/files/babelrc-flow.js' {
  declare module.exports: $Exports<'@backtrack/preset-node-module/lib/files/babelrc-flow'>;
}
declare module '@backtrack/preset-node-module/lib/files/babelrc.js' {
  declare module.exports: $Exports<'@backtrack/preset-node-module/lib/files/babelrc'>;
}
declare module '@backtrack/preset-node-module/lib/files/package-entry-flow.js' {
  declare module.exports: $Exports<'@backtrack/preset-node-module/lib/files/package-entry-flow'>;
}
declare module '@backtrack/preset-node-module/lib/files/package-entry.js' {
  declare module.exports: $Exports<'@backtrack/preset-node-module/lib/files/package-entry'>;
}
declare module '@backtrack/preset-node-module/lib/preset-node-module.js' {
  declare module.exports: $Exports<'@backtrack/preset-node-module/lib/preset-node-module'>;
}
declare module '@backtrack/preset-node-module/lib/preset-node-module.test.js' {
  declare module.exports: $Exports<'@backtrack/preset-node-module/lib/preset-node-module.test'>;
}
